dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: JmKLMkHbdDtHCoKJW4O33buI1qdFXxpLWi1cCyzHVu1lziEwREd+jrOhMnWVoyunPuJGkyf5HSYiXBcuT7QuMsyAScbhFwj9AvUL8i8nmEGP+OP2JDUPAcEsAbOLQhBEBZhsocu/wB6jJduKs+o9Uw+oLcgomwXURYLOJpuT3rreWiuh0ujMChkQqt3SWbK7HK91guyoEKmtOeMVzAAx2dywbH3s39KPWFGnIbg5xoT8kykorCPKWiv4Dle5AR6OjteSsPhWcTrUAYYzNv0RgjB0P9WFIDIMAt69CoxyTF03nzGBNy0TmLDFwvJJ8kOgZXG6AgYCKJg19qYMNciXu5vIftLLEsBG2c5cWCPDeYyrYUZ+Jqr2cuqP5BAXCdkeVfS6B92/9j+gIuPshoNAxzBjq6paqALk94NRyJKnKJ2lAhHyPTZFaEXxF2UrsicL6kq2oOL3HDQavu7EaZ1OaBuiO1M94b5yPb0TUCstmUlrQvRy/xSHU78ptK7o5xug1WU4hhvx3LE8f98dlSTTQm/b7psrS8PvPoS5yhV3Go+Vng2G9OlEnrLRr08d1nVPOPW9R0wzhAtsnqokh0Idq2oLslPUHXSURnkNSTkbfY9HpLOWflgKnt+Gd2FWqp8em4zXTf23xVyonYcO8v7tGnFKNFsInR9Kt3FEIrrT2rA=
