dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: qlygybiJNTGxXrkwFPkPx408XMCT5lgKEmCkB2KZTHWzObVfo0Nmx6/sNwt2fF6cmlQC78CVE9mnYUj3ec/+yDA9bY5XAd+xEsWzCo1X0LHYOfiTJCc6fnk7shhWrD6pbxbXlHbw8MCqT3ZlXr9nt3KhkqpjbRr9dNtrC+MTtw7H+mTjOEuj0cVFAnpAUydEIysminvN83dOe3VExQtKfssWEMaVTEBcSv7zpW9IyHKmWGcTYlwIIgu7FqiJj2nLXEZ5L44drX1vm4871tA1AD7v4o/GYkF7Alsf2Ex22Ytio6IzCV9yp3aIKRZbyUQjsB5TnATkVZrFkgLRt+kasWrNHytExJgg0g2l63dutdfa5xmP6YikHzTd1PMzy5D8YHdbZLr59fsY6cUosQCH2tHofiPEjWqsBITo6hUSPQfJUTH59Is71BYsf/dFKDYaXUwmeZ3ZGbETUVEXU1sBfG3kN7aRT6uBqGASQ0k2/72n9v7TvgyFA+ZwycSp6o/Sg5IDkLFrq8hh5tHiqnvDd1xzfz7Oq8xZCjPOgTwO4dqFn3OgBh/VHsMa5yB77WrurjXl71cs7vdTdT6taAISdV1FHjBaSVgTt9aqvhSGbe6GbRMoCY9WYgkOUVFQtwbwzeYaOiX7fc4I8rnHB2ZodUa5C1r/lF2viX25fDvO71A=
