version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - reddit
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
volumes:
  post_db:
  prometheus_data:

networks:
  reddit:

