version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - reddit

  elasticsearch:
    image: elasticsearch:5.6
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - reddit

  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"
    networks:
      - reddit

networks:
  reddit:

