- hosts: all
  become: true
  vars:
    docker_ecs_login_password: "{{ lookup('env','ECS_LOGIN_PASSWORD') }}"
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages"
  tasks:
  - name: Run reddit docker container
    docker_container:
      name: reddit
      image: svitru/otus-reddit:1.0
      state: started
      ports:
      - "9292:9292"

